# Generated by Django 4.1.2 on 2022-10-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('version', models.IntegerField()),
                ('length_ms', models.IntegerField()),
            ],
        ),
    ]
